/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StandardSeries.Lines;

import com.steema.teechart.TChart;
import com.steema.teechart.drawing.Color;
import com.steema.teechart.editors.ChartEditor;
import com.steema.teechart.legend.LegendAlignment;
import com.steema.teechart.styles.ArrowHeadStyle;
import com.steema.teechart.styles.Line;
import com.steema.teechart.styles.PointerStyle;
import com.steema.teechart.tools.MarksTip;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author norike
 */
public class StockMonitoring extends javax.swing.JPanel {

    /**
     * Creates new form StockMonitoring
     */
    public StockMonitoring() {
        initComponents();
        
        createChart();
        initChart();        
        setEditor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    protected TChart tChart1;
    
    private void createChart() {
        tChart1 = new TChart();
        add(tChart1);
    }

    private void initChart() {
        tChart1.getWalls().getBack().setVisible(false);
        tChart1.getPanel().getGradient().setVisible(false);
        tChart1.getHeader().getFont().setColor(Color.BLACK);
        tChart1.getHeader().getFont().setSize(19);
        tChart1.getHeader().getFont().setName("Roboto Th");
        tChart1.getHeader().getFont().setBold(true);
        tChart1.getHeader().getFont().getShadow().setColor(Color.GRAY);
        tChart1.getHeader().getFont().getShadow().setHorizSize(1);
        tChart1.getHeader().getFont().getShadow().setVertSize(1);
        tChart1.getHeader().getFont().getShadow().setSmoothBlur(2);
        tChart1.getHeader().getFont().getShadow().setVisible(true);
        tChart1.getHeader().setText("Stock Monitoring");
        tChart1.getAxes().getBottom().getAxisPen().setColor(Color.fromArgb(110, 110, 110));
        tChart1.getAxes().getBottom().getAxisPen().setWidth(1);
        tChart1.getAxes().getBottom().getLabels().setDateTimeFormat("yyyy-mm-dd");
        tChart1.getAxes().getBottom().getGrid().setVisible(false);
        tChart1.getAxes().getBottom().getLabels().getFont().setColor(Color.GRAY);
        tChart1.getAxes().getBottom().getLabels().getFont().setSize(16);
        tChart1.getAxes().getBottom().getLabels().getFont().setName("Segoe UI");
        tChart1.getAxes().getBottom().getMinorTicks().setVisible(false);
        tChart1.getAxes().getBottom().getTicksInner().setVisible(false);
        tChart1.getAxes().getBottom().getTitle().getFont().setSize(13);
        tChart1.getAxes().getBottom().getTitle().getFont().setName("Roboto Th");
        tChart1.getAxes().getLeft().getAxisPen().setVisible(false);
        tChart1.getAxes().getLeft().getGrid().setColor(Color.fromArgb(221, 221, 221));
        tChart1.getAxes().getLeft().getLabels().getFont().setColor(Color.GRAY);
        tChart1.getAxes().getLeft().getLabels().getFont().setSize(16);
        tChart1.getAxes().getLeft().getLabels().getFont().setName("Segoe UI");
        tChart1.getAxes().getLeft().getMinorTicks().setVisible(false);
        tChart1.getAxes().getLeft().getTicks().setLength(7);
        tChart1.getAxes().getLeft().getTicks().setTransparency(100);
        tChart1.getAxes().getLeft().getTicksInner().setVisible(false);
        tChart1.getAxes().getLeft().getTitle().setCaption("Quote");
        tChart1.getAxes().getLeft().getTitle().getFont().setColor(Color.GRAY);
        tChart1.getAxes().getLeft().getTitle().getFont().setSize(13);
        tChart1.getAxes().getLeft().getTitle().getFont().setName("Segoe UI");
        tChart1.getLegend().setAlignment(LegendAlignment.BOTTOM);
        tChart1.getLegend().getPen().setVisible(false);
        tChart1.getLegend().getFont().setColor(Color.GRAY);
        tChart1.getLegend().getFont().setSize(13);
        tChart1.getLegend().getFont().setName("Segoe UI");
        tChart1.getLegend().getShadow().setVisible(false);
        tChart1.getLegend().getSymbol().getPen().setVisible(false);
        tChart1.getAspect().setView3D(false);
        tChart1.getPanel().setColor(Color.WHITE);
        
        Line line1 = new Line(tChart1.getChart());
        Line line2 = new Line(tChart1.getChart());
        Line line3 = new Line(tChart1.getChart());
        
        line1.setColor(new Color(255, 153, 102));
        line2.setColor(new Color(0, 128, 255));
        line3.setColor(new Color(128, 255, 128));
        
        initSeries(line1);
        initSeries(line2);
        initSeries(line3);
        
        line1.setTitle("Portfolio 1");
        line2.setTitle("Portfolio 2");
        line3.setTitle("Portfolio 3");
        
        line1.fillSampleValues(12);
        line2.fillSampleValues(10);
        line3.fillSampleValues(11);
        
        MarksTip marksTip1 = new MarksTip(tChart1.getChart());
        marksTip1.setHideDelay(2000);
        marksTip1.setMouseDelay(100);
        /*marksTip1.getFormat().setColor = 4227327
        marksTip1.getFormat().setCustomPosition(true);
        marksTip1.getFormat().getFont().setColor(Color.GRAY);
        marksTip1.getFormat().getFont().setSize(28);
        marksTip1.getFormat().setLeft(0);
        marksTip1.getFormat().setTextAlignment(CENTER);
        marksTip1.getFormat().setTop(0);
        marksTip1.getFormat().setTransparent(true);
        marksTip1.getFormat().setVisible(false);*/
    }

    private void setEditor() {
        tChart1.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                 if (e.getClickCount()==2) {
                    ChartEditor.editChart(tChart1.getChart());
                }
            }
        });
    }

    private Line initSeries(Line line) {
        line.getMarks().getFont().setSize(24);
        line.getMarks().getFont().setName("Roboto Th");
        line.getMarks().setTransparent(true);
        line.getMarks().getArrow().setVisible(false);
        line.getMarks().getCallout().getArrow().setVisible(false);
        line.getMarks().getCallout().setArrowHead(ArrowHeadStyle.LINE);
        line.getMarks().getCallout().setDistance(8);
        line.getMarks().getCallout().setLength(0);
        //ValueFormat = '#.##0,###'
        line.getLinePen().setWidth(3);
        line.getPointer().setHorizSize(6);
        line.getPointer().setInflateMargins(true);
        line.getPointer().getPen().setColor(line.getColor());
        line.getPointer().setColor(Color.WHITE);
        line.getPointer().getPen().setWidth(3);
        line.getPointer().setStyle(PointerStyle.CIRCLE);
        line.getPointer().setVertSize(6);
        line.getPointer().setVisible(true);
        
        line.getXValues().setDateTime(true);
        
        return line;
    }
}
