/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StandardSeries;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import StandardSeries.Areas.VegetationGrowth;
import StandardSeries.Bars.SalesFigures;
import StandardSeries.Bars.ServerStatus;
import StandardSeries.Bars.StackedBars;
import StandardSeries.Bubbles.PopularCodeLanguages;
import StandardSeries.Gantt.ProjectPlanner;
import StandardSeries.Lines.StockMonitoring;
import StandardSeries.Lines.WebAnalytics;
import StandardSeries.Miscellaneous.ScrollerChart;
import StandardSeries.Miscellaneous.StartForm;
import StandardSeries.PieAndDonut.DonutChart;
import StandardSeries.PieAndDonut.MultiDonut;
import StandardSeries.PieAndDonut.MultiPies;
import StandardSeries.PieAndDonut.PieSalesFigures;
import StandardSeries.Points.ProductShipments;

/**
 *
 * @author norike
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);

        setButtonsListeners();

        setPlainFonts();

        showChart(new StartForm());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChart = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblImgTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        pnlContact = new javax.swing.JPanel();
        lblContact = new javax.swing.JLabel();
        lblDescript = new javax.swing.JLabel();
        btnWeb = new javax.swing.JButton();
        pnlMenuGroups = new javax.swing.JPanel();
        pnlMenuLines = new javax.swing.JPanel();
        btnGroupLines = new javax.swing.JButton();
        btnStockMonitoring = new javax.swing.JButton();
        btnWebAnalytics = new javax.swing.JButton();
        pnlMenuBars = new javax.swing.JPanel();
        btnGroupBars = new javax.swing.JButton();
        btnSalesFigures = new javax.swing.JButton();
        btnStackedBars = new javax.swing.JButton();
        btnServerStatus = new javax.swing.JButton();
        pnlMenuAreas = new javax.swing.JPanel();
        btnGroupAreas = new javax.swing.JButton();
        btnVegetationGrowth = new javax.swing.JButton();
        pnlMenuPieDonut = new javax.swing.JPanel();
        btnGroupPieDonut = new javax.swing.JButton();
        btnSalesFiguresPie = new javax.swing.JButton();
        btnMultiplePies = new javax.swing.JButton();
        btnDonut = new javax.swing.JButton();
        btnMultiDonut = new javax.swing.JButton();
        pnlMenuPoints = new javax.swing.JPanel();
        btnGroupPoints = new javax.swing.JButton();
        btnProductShipments = new javax.swing.JButton();
        pnlMenuGantt = new javax.swing.JPanel();
        btnGroupGantt = new javax.swing.JButton();
        btnProjectPlanner = new javax.swing.JButton();
        pnlMenuBubbles = new javax.swing.JPanel();
        btnGroupBubbles = new javax.swing.JButton();
        btnPopularCodeLanguages = new javax.swing.JButton();
        pnlMenuMiscellaneous = new javax.swing.JPanel();
        btnGroupMiscellaneous = new javax.swing.JButton();
        btnScroller = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TeeChart Java for Swing - Standard Series types Example - www.steema.com");

        pnlChart.setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(java.awt.Color.gray);
        pnlMenu.setOpaque(false);
        pnlMenu.setPreferredSize(new java.awt.Dimension(150, 169));

        pnlTitle.setBackground(new java.awt.Color(105, 105, 105));

        lblImgTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/TeeChartWhite190x44.png"))); // NOI18N
        lblImgTitle.setPreferredSize(new java.awt.Dimension(190, 52));

        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Standard Series");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setPreferredSize(new java.awt.Dimension(76, 24));

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImgTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addComponent(lblImgTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlContact.setBackground(new java.awt.Color(153, 204, 255));
        pnlContact.setLayout(new java.awt.BorderLayout());

        lblContact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContact.setText("Contact information:");
        lblContact.setPreferredSize(new java.awt.Dimension(99, 24));
        pnlContact.add(lblContact, java.awt.BorderLayout.NORTH);

        lblDescript.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescript.setText("Steema Software. Home of TeeChart");
        pnlContact.add(lblDescript, java.awt.BorderLayout.CENTER);

        btnWeb.setBackground(new java.awt.Color(255, 255, 255));
        btnWeb.setForeground(new java.awt.Color(255, 255, 255));
        btnWeb.setText("<HTML><U>http://www.steema.com</U></HTML>\"");
        btnWeb.setToolTipText("http://www.stwwma.com");
        btnWeb.setBorder(null);
        btnWeb.setBorderPainted(false);
        btnWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWeb.setOpaque(false);
        btnWeb.setPreferredSize(new java.awt.Dimension(119, 25));
        btnWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebActionPerformed(evt);
            }
        });
        pnlContact.add(btnWeb, java.awt.BorderLayout.SOUTH);

        pnlMenuGroups.setBackground(new java.awt.Color(128, 128, 128));

        pnlMenuLines.setBackground(new java.awt.Color(105, 105, 105));
        pnlMenuLines.setMaximumSize(new java.awt.Dimension(200, 68));
        pnlMenuLines.setPreferredSize(new java.awt.Dimension(200, 68));

        btnGroupLines.setBackground(new java.awt.Color(128, 128, 128));
        btnGroupLines.setForeground(new java.awt.Color(204, 255, 255));
        btnGroupLines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/up.png"))); // NOI18N
        btnGroupLines.setText("Lines");
        btnGroupLines.setBorderPainted(false);
        btnGroupLines.setFocusPainted(false);
        btnGroupLines.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGroupLines.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGroupLines.setIconTextGap(119);
        btnGroupLines.setMaximumSize(new java.awt.Dimension(200, 32));
        btnGroupLines.setMinimumSize(new java.awt.Dimension(191, 32));
        btnGroupLines.setPreferredSize(new java.awt.Dimension(200, 32));
        btnGroupLines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnGroupLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupLinesActionPerformed(evt);
            }
        });

        btnStockMonitoring.setBackground(new java.awt.Color(169, 169, 169));
        btnStockMonitoring.setForeground(new java.awt.Color(255, 255, 255));
        btnStockMonitoring.setText("Stock Monitoring");
        btnStockMonitoring.setBorderPainted(false);
        btnStockMonitoring.setFocusPainted(false);
        btnStockMonitoring.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStockMonitoring.setMaximumSize(new java.awt.Dimension(200, 32));
        btnStockMonitoring.setMinimumSize(new java.awt.Dimension(191, 32));
        btnStockMonitoring.setPreferredSize(new java.awt.Dimension(200, 32));
        btnStockMonitoring.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        btnWebAnalytics.setBackground(new java.awt.Color(169, 169, 169));
        btnWebAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        btnWebAnalytics.setText("Web Analytics");
        btnWebAnalytics.setToolTipText("");
        btnWebAnalytics.setBorderPainted(false);
        btnWebAnalytics.setFocusPainted(false);
        btnWebAnalytics.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnWebAnalytics.setMaximumSize(new java.awt.Dimension(200, 32));
        btnWebAnalytics.setMinimumSize(new java.awt.Dimension(191, 32));
        btnWebAnalytics.setPreferredSize(new java.awt.Dimension(200, 32));
        btnWebAnalytics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLinesLayout = new javax.swing.GroupLayout(pnlMenuLines);
        pnlMenuLines.setLayout(pnlMenuLinesLayout);
        pnlMenuLinesLayout.setHorizontalGroup(
            pnlMenuLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGroupLines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnStockMonitoring, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnWebAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuLinesLayout.setVerticalGroup(
            pnlMenuLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLinesLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnGroupLines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnStockMonitoring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnWebAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuBars.setBackground(new java.awt.Color(105, 105, 105));
        pnlMenuBars.setMaximumSize(new java.awt.Dimension(200, 68));
        pnlMenuBars.setPreferredSize(new java.awt.Dimension(200, 68));

        btnGroupBars.setBackground(new java.awt.Color(128, 128, 128));
        btnGroupBars.setForeground(new java.awt.Color(204, 255, 255));
        btnGroupBars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/down.png"))); // NOI18N
        btnGroupBars.setText("Bars");
        btnGroupBars.setBorderPainted(false);
        btnGroupBars.setFocusPainted(false);
        btnGroupBars.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGroupBars.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGroupBars.setIconTextGap(124);
        btnGroupBars.setMaximumSize(new java.awt.Dimension(200, 32));
        btnGroupBars.setMinimumSize(new java.awt.Dimension(191, 32));
        btnGroupBars.setPreferredSize(new java.awt.Dimension(200, 32));
        btnGroupBars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnGroupBars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupBarsActionPerformed(evt);
            }
        });

        btnSalesFigures.setBackground(new java.awt.Color(169, 169, 169));
        btnSalesFigures.setForeground(new java.awt.Color(255, 255, 255));
        btnSalesFigures.setText("Sales Figures");
        btnSalesFigures.setBorderPainted(false);
        btnSalesFigures.setFocusPainted(false);
        btnSalesFigures.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalesFigures.setMaximumSize(new java.awt.Dimension(200, 32));
        btnSalesFigures.setMinimumSize(new java.awt.Dimension(191, 32));
        btnSalesFigures.setPreferredSize(new java.awt.Dimension(200, 32));
        btnSalesFigures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        btnStackedBars.setBackground(new java.awt.Color(169, 169, 169));
        btnStackedBars.setForeground(new java.awt.Color(255, 255, 255));
        btnStackedBars.setText("Stacked Bars");
        btnStackedBars.setToolTipText("");
        btnStackedBars.setBorderPainted(false);
        btnStackedBars.setFocusPainted(false);
        btnStackedBars.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStackedBars.setMaximumSize(new java.awt.Dimension(200, 32));
        btnStackedBars.setMinimumSize(new java.awt.Dimension(191, 32));
        btnStackedBars.setPreferredSize(new java.awt.Dimension(200, 32));
        btnStackedBars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        btnServerStatus.setBackground(new java.awt.Color(169, 169, 169));
        btnServerStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnServerStatus.setText("Server Status");
        btnServerStatus.setToolTipText("");
        btnServerStatus.setBorderPainted(false);
        btnServerStatus.setFocusPainted(false);
        btnServerStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnServerStatus.setMaximumSize(new java.awt.Dimension(200, 32));
        btnServerStatus.setMinimumSize(new java.awt.Dimension(191, 32));
        btnServerStatus.setPreferredSize(new java.awt.Dimension(200, 32));
        btnServerStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuBarsLayout = new javax.swing.GroupLayout(pnlMenuBars);
        pnlMenuBars.setLayout(pnlMenuBarsLayout);
        pnlMenuBarsLayout.setHorizontalGroup(
            pnlMenuBarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGroupBars, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSalesFigures, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnStackedBars, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnServerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuBarsLayout.setVerticalGroup(
            pnlMenuBarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarsLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnGroupBars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSalesFigures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnStackedBars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnServerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuAreas.setBackground(new java.awt.Color(105, 105, 105));
        pnlMenuAreas.setMaximumSize(new java.awt.Dimension(200, 68));
        pnlMenuAreas.setPreferredSize(new java.awt.Dimension(200, 68));

        btnGroupAreas.setBackground(new java.awt.Color(128, 128, 128));
        btnGroupAreas.setForeground(new java.awt.Color(204, 255, 255));
        btnGroupAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/down.png"))); // NOI18N
        btnGroupAreas.setText("Areas");
        btnGroupAreas.setBorderPainted(false);
        btnGroupAreas.setFocusPainted(false);
        btnGroupAreas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGroupAreas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGroupAreas.setIconTextGap(117);
        btnGroupAreas.setMaximumSize(new java.awt.Dimension(200, 32));
        btnGroupAreas.setMinimumSize(new java.awt.Dimension(191, 32));
        btnGroupAreas.setPreferredSize(new java.awt.Dimension(200, 32));
        btnGroupAreas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnGroupAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupAreasActionPerformed(evt);
            }
        });

        btnVegetationGrowth.setBackground(new java.awt.Color(169, 169, 169));
        btnVegetationGrowth.setForeground(new java.awt.Color(255, 255, 255));
        btnVegetationGrowth.setText("Vegetation Growth");
        btnVegetationGrowth.setBorderPainted(false);
        btnVegetationGrowth.setFocusPainted(false);
        btnVegetationGrowth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVegetationGrowth.setMaximumSize(new java.awt.Dimension(200, 32));
        btnVegetationGrowth.setMinimumSize(new java.awt.Dimension(191, 32));
        btnVegetationGrowth.setPreferredSize(new java.awt.Dimension(200, 32));
        btnVegetationGrowth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuAreasLayout = new javax.swing.GroupLayout(pnlMenuAreas);
        pnlMenuAreas.setLayout(pnlMenuAreasLayout);
        pnlMenuAreasLayout.setHorizontalGroup(
            pnlMenuAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGroupAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnVegetationGrowth, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuAreasLayout.setVerticalGroup(
            pnlMenuAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuAreasLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnGroupAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVegetationGrowth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuPieDonut.setBackground(new java.awt.Color(105, 105, 105));
        pnlMenuPieDonut.setMaximumSize(new java.awt.Dimension(200, 68));
        pnlMenuPieDonut.setPreferredSize(new java.awt.Dimension(200, 68));

        btnGroupPieDonut.setBackground(new java.awt.Color(128, 128, 128));
        btnGroupPieDonut.setForeground(new java.awt.Color(204, 255, 255));
        btnGroupPieDonut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/down.png"))); // NOI18N
        btnGroupPieDonut.setText("Pie and Donut");
        btnGroupPieDonut.setBorderPainted(false);
        btnGroupPieDonut.setFocusPainted(false);
        btnGroupPieDonut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGroupPieDonut.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGroupPieDonut.setIconTextGap(72);
        btnGroupPieDonut.setMaximumSize(new java.awt.Dimension(200, 32));
        btnGroupPieDonut.setMinimumSize(new java.awt.Dimension(191, 32));
        btnGroupPieDonut.setPreferredSize(new java.awt.Dimension(200, 32));
        btnGroupPieDonut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnGroupPieDonut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupPieDonutActionPerformed(evt);
            }
        });

        btnSalesFiguresPie.setBackground(new java.awt.Color(169, 169, 169));
        btnSalesFiguresPie.setForeground(new java.awt.Color(255, 255, 255));
        btnSalesFiguresPie.setText("Sales Figures");
        btnSalesFiguresPie.setBorderPainted(false);
        btnSalesFiguresPie.setFocusPainted(false);
        btnSalesFiguresPie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalesFiguresPie.setMaximumSize(new java.awt.Dimension(200, 32));
        btnSalesFiguresPie.setMinimumSize(new java.awt.Dimension(191, 32));
        btnSalesFiguresPie.setPreferredSize(new java.awt.Dimension(200, 32));
        btnSalesFiguresPie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        btnMultiplePies.setBackground(new java.awt.Color(169, 169, 169));
        btnMultiplePies.setForeground(new java.awt.Color(255, 255, 255));
        btnMultiplePies.setText("Multiple Pies");
        btnMultiplePies.setToolTipText("");
        btnMultiplePies.setBorderPainted(false);
        btnMultiplePies.setFocusPainted(false);
        btnMultiplePies.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMultiplePies.setMaximumSize(new java.awt.Dimension(200, 32));
        btnMultiplePies.setMinimumSize(new java.awt.Dimension(191, 32));
        btnMultiplePies.setPreferredSize(new java.awt.Dimension(200, 32));
        btnMultiplePies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        btnDonut.setBackground(new java.awt.Color(169, 169, 169));
        btnDonut.setForeground(new java.awt.Color(255, 255, 255));
        btnDonut.setText("Donut");
        btnDonut.setToolTipText("");
        btnDonut.setBorderPainted(false);
        btnDonut.setFocusPainted(false);
        btnDonut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDonut.setMaximumSize(new java.awt.Dimension(200, 32));
        btnDonut.setMinimumSize(new java.awt.Dimension(191, 32));
        btnDonut.setPreferredSize(new java.awt.Dimension(200, 32));
        btnDonut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        btnMultiDonut.setBackground(new java.awt.Color(169, 169, 169));
        btnMultiDonut.setForeground(new java.awt.Color(255, 255, 255));
        btnMultiDonut.setText("Multi Donut");
        btnMultiDonut.setToolTipText("");
        btnMultiDonut.setBorderPainted(false);
        btnMultiDonut.setFocusPainted(false);
        btnMultiDonut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMultiDonut.setMaximumSize(new java.awt.Dimension(200, 32));
        btnMultiDonut.setMinimumSize(new java.awt.Dimension(191, 32));
        btnMultiDonut.setPreferredSize(new java.awt.Dimension(200, 32));
        btnMultiDonut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuPieDonutLayout = new javax.swing.GroupLayout(pnlMenuPieDonut);
        pnlMenuPieDonut.setLayout(pnlMenuPieDonutLayout);
        pnlMenuPieDonutLayout.setHorizontalGroup(
            pnlMenuPieDonutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGroupPieDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSalesFiguresPie, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMultiplePies, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMultiDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuPieDonutLayout.setVerticalGroup(
            pnlMenuPieDonutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuPieDonutLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnGroupPieDonut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSalesFiguresPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMultiplePies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDonut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMultiDonut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuPoints.setBackground(new java.awt.Color(105, 105, 105));
        pnlMenuPoints.setMaximumSize(new java.awt.Dimension(200, 68));
        pnlMenuPoints.setPreferredSize(new java.awt.Dimension(200, 68));

        btnGroupPoints.setBackground(new java.awt.Color(128, 128, 128));
        btnGroupPoints.setForeground(new java.awt.Color(204, 255, 255));
        btnGroupPoints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/down.png"))); // NOI18N
        btnGroupPoints.setText("Points");
        btnGroupPoints.setBorderPainted(false);
        btnGroupPoints.setFocusPainted(false);
        btnGroupPoints.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGroupPoints.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGroupPoints.setIconTextGap(115);
        btnGroupPoints.setMaximumSize(new java.awt.Dimension(200, 32));
        btnGroupPoints.setMinimumSize(new java.awt.Dimension(191, 32));
        btnGroupPoints.setPreferredSize(new java.awt.Dimension(200, 32));
        btnGroupPoints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnGroupPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupPointsActionPerformed(evt);
            }
        });

        btnProductShipments.setBackground(new java.awt.Color(169, 169, 169));
        btnProductShipments.setForeground(new java.awt.Color(255, 255, 255));
        btnProductShipments.setText("Product Shipments");
        btnProductShipments.setBorderPainted(false);
        btnProductShipments.setFocusPainted(false);
        btnProductShipments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductShipments.setMaximumSize(new java.awt.Dimension(200, 32));
        btnProductShipments.setMinimumSize(new java.awt.Dimension(191, 32));
        btnProductShipments.setPreferredSize(new java.awt.Dimension(200, 32));
        btnProductShipments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuPointsLayout = new javax.swing.GroupLayout(pnlMenuPoints);
        pnlMenuPoints.setLayout(pnlMenuPointsLayout);
        pnlMenuPointsLayout.setHorizontalGroup(
            pnlMenuPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGroupPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnProductShipments, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuPointsLayout.setVerticalGroup(
            pnlMenuPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuPointsLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnGroupPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnProductShipments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuGantt.setBackground(new java.awt.Color(105, 105, 105));
        pnlMenuGantt.setMaximumSize(new java.awt.Dimension(200, 68));
        pnlMenuGantt.setPreferredSize(new java.awt.Dimension(200, 68));

        btnGroupGantt.setBackground(new java.awt.Color(128, 128, 128));
        btnGroupGantt.setForeground(new java.awt.Color(204, 255, 255));
        btnGroupGantt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/down.png"))); // NOI18N
        btnGroupGantt.setText("Gantt");
        btnGroupGantt.setBorderPainted(false);
        btnGroupGantt.setFocusPainted(false);
        btnGroupGantt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGroupGantt.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGroupGantt.setIconTextGap(121);
        btnGroupGantt.setMaximumSize(new java.awt.Dimension(200, 32));
        btnGroupGantt.setMinimumSize(new java.awt.Dimension(191, 32));
        btnGroupGantt.setPreferredSize(new java.awt.Dimension(200, 32));
        btnGroupGantt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnGroupGantt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupGanttActionPerformed(evt);
            }
        });

        btnProjectPlanner.setBackground(new java.awt.Color(169, 169, 169));
        btnProjectPlanner.setForeground(new java.awt.Color(255, 255, 255));
        btnProjectPlanner.setText("Project Planner");
        btnProjectPlanner.setBorderPainted(false);
        btnProjectPlanner.setFocusPainted(false);
        btnProjectPlanner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProjectPlanner.setMaximumSize(new java.awt.Dimension(200, 32));
        btnProjectPlanner.setMinimumSize(new java.awt.Dimension(191, 32));
        btnProjectPlanner.setPreferredSize(new java.awt.Dimension(200, 32));
        btnProjectPlanner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuGanttLayout = new javax.swing.GroupLayout(pnlMenuGantt);
        pnlMenuGantt.setLayout(pnlMenuGanttLayout);
        pnlMenuGanttLayout.setHorizontalGroup(
            pnlMenuGanttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGroupGantt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnProjectPlanner, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuGanttLayout.setVerticalGroup(
            pnlMenuGanttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuGanttLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnGroupGantt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnProjectPlanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuBubbles.setBackground(new java.awt.Color(105, 105, 105));
        pnlMenuBubbles.setMaximumSize(new java.awt.Dimension(200, 68));
        pnlMenuBubbles.setPreferredSize(new java.awt.Dimension(200, 68));

        btnGroupBubbles.setBackground(new java.awt.Color(128, 128, 128));
        btnGroupBubbles.setForeground(new java.awt.Color(204, 255, 255));
        btnGroupBubbles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/down.png"))); // NOI18N
        btnGroupBubbles.setText("Bubbles");
        btnGroupBubbles.setBorderPainted(false);
        btnGroupBubbles.setFocusPainted(false);
        btnGroupBubbles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGroupBubbles.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGroupBubbles.setIconTextGap(104);
        btnGroupBubbles.setMaximumSize(new java.awt.Dimension(200, 32));
        btnGroupBubbles.setMinimumSize(new java.awt.Dimension(191, 32));
        btnGroupBubbles.setPreferredSize(new java.awt.Dimension(200, 32));
        btnGroupBubbles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnGroupBubbles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupBubblesActionPerformed(evt);
            }
        });

        btnPopularCodeLanguages.setBackground(new java.awt.Color(169, 169, 169));
        btnPopularCodeLanguages.setForeground(new java.awt.Color(255, 255, 255));
        btnPopularCodeLanguages.setText("Popular Code Languages");
        btnPopularCodeLanguages.setBorderPainted(false);
        btnPopularCodeLanguages.setFocusPainted(false);
        btnPopularCodeLanguages.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPopularCodeLanguages.setMaximumSize(new java.awt.Dimension(200, 32));
        btnPopularCodeLanguages.setMinimumSize(new java.awt.Dimension(191, 32));
        btnPopularCodeLanguages.setPreferredSize(new java.awt.Dimension(200, 32));
        btnPopularCodeLanguages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuBubblesLayout = new javax.swing.GroupLayout(pnlMenuBubbles);
        pnlMenuBubbles.setLayout(pnlMenuBubblesLayout);
        pnlMenuBubblesLayout.setHorizontalGroup(
            pnlMenuBubblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGroupBubbles, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnPopularCodeLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuBubblesLayout.setVerticalGroup(
            pnlMenuBubblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBubblesLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnGroupBubbles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPopularCodeLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuMiscellaneous.setBackground(new java.awt.Color(105, 105, 105));
        pnlMenuMiscellaneous.setMaximumSize(new java.awt.Dimension(200, 68));
        pnlMenuMiscellaneous.setPreferredSize(new java.awt.Dimension(200, 68));

        btnGroupMiscellaneous.setBackground(new java.awt.Color(128, 128, 128));
        btnGroupMiscellaneous.setForeground(new java.awt.Color(204, 255, 255));
        btnGroupMiscellaneous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/down.png"))); // NOI18N
        btnGroupMiscellaneous.setText("Miscellaneous");
        btnGroupMiscellaneous.setBorderPainted(false);
        btnGroupMiscellaneous.setFocusPainted(false);
        btnGroupMiscellaneous.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGroupMiscellaneous.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGroupMiscellaneous.setIconTextGap(70);
        btnGroupMiscellaneous.setMaximumSize(new java.awt.Dimension(200, 32));
        btnGroupMiscellaneous.setMinimumSize(new java.awt.Dimension(191, 32));
        btnGroupMiscellaneous.setPreferredSize(new java.awt.Dimension(200, 32));
        btnGroupMiscellaneous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnGroupMiscellaneous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupMiscellaneousActionPerformed(evt);
            }
        });

        btnScroller.setBackground(new java.awt.Color(169, 169, 169));
        btnScroller.setForeground(new java.awt.Color(255, 255, 255));
        btnScroller.setText("Scroller");
        btnScroller.setBorderPainted(false);
        btnScroller.setFocusPainted(false);
        btnScroller.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnScroller.setMaximumSize(new java.awt.Dimension(200, 32));
        btnScroller.setMinimumSize(new java.awt.Dimension(191, 32));
        btnScroller.setPreferredSize(new java.awt.Dimension(200, 32));
        btnScroller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSampleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuMiscellaneousLayout = new javax.swing.GroupLayout(pnlMenuMiscellaneous);
        pnlMenuMiscellaneous.setLayout(pnlMenuMiscellaneousLayout);
        pnlMenuMiscellaneousLayout.setHorizontalGroup(
            pnlMenuMiscellaneousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGroupMiscellaneous, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuMiscellaneousLayout.setVerticalGroup(
            pnlMenuMiscellaneousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuMiscellaneousLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnGroupMiscellaneous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnScroller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMenuGroupsLayout = new javax.swing.GroupLayout(pnlMenuGroups);
        pnlMenuGroups.setLayout(pnlMenuGroupsLayout);
        pnlMenuGroupsLayout.setHorizontalGroup(
            pnlMenuGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuLines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlMenuBars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlMenuAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlMenuPieDonut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlMenuPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlMenuGantt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlMenuBubbles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlMenuMiscellaneous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuGroupsLayout.setVerticalGroup(
            pnlMenuGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuGroupsLayout.createSequentialGroup()
                .addComponent(pnlMenuLines, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuBars, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuPieDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuGantt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuBubbles, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuMiscellaneous, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuGroups, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuGroups, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlContact, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Events">
    private void btnWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI("http://www.steema.com"));
            } catch (IOException | URISyntaxException e) {
            }
        }
    }//GEN-LAST:event_btnWebActionPerformed

    private void btnGroupLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupLinesActionPerformed
        expandCollapse(pnlMenuLines, btnGroupLines, 2);
    }//GEN-LAST:event_btnGroupLinesActionPerformed

    private void btnSampleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSampleMouseEntered
        ((JButton) evt.getSource()).setBackground(new Color(152, 152, 152));
    }//GEN-LAST:event_btnSampleMouseEntered

    private void btnSampleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSampleMouseExited
        ((JButton) evt.getSource()).setBackground(new Color(169, 169, 169));
    }//GEN-LAST:event_btnSampleMouseExited

    private void btnGroupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroupMouseEntered
        ((JButton) evt.getSource()).setBackground(new Color(115, 115, 115));
    }//GEN-LAST:event_btnGroupMouseEntered

    private void btnGroupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroupMouseExited
        ((JButton) evt.getSource()).setBackground(new Color(128, 128, 128));
    }//GEN-LAST:event_btnGroupMouseExited

    private void btnGroupAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupAreasActionPerformed
        expandCollapse(pnlMenuAreas, btnGroupAreas, 1);
    }//GEN-LAST:event_btnGroupAreasActionPerformed

    private void btnGroupPieDonutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupPieDonutActionPerformed
        expandCollapse(pnlMenuPieDonut, btnGroupPieDonut, 4);
    }//GEN-LAST:event_btnGroupPieDonutActionPerformed

    private void btnGroupPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupPointsActionPerformed
        expandCollapse(pnlMenuPoints, btnGroupPoints, 1);
    }//GEN-LAST:event_btnGroupPointsActionPerformed

    private void btnGroupGanttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupGanttActionPerformed
        expandCollapse(pnlMenuGantt, btnGroupGantt, 1);
    }//GEN-LAST:event_btnGroupGanttActionPerformed

    private void btnGroupBubblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupBubblesActionPerformed
        expandCollapse(pnlMenuBubbles, btnGroupBubbles, 1);
    }//GEN-LAST:event_btnGroupBubblesActionPerformed

    private void btnGroupMiscellaneousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupMiscellaneousActionPerformed
        expandCollapse(pnlMenuMiscellaneous, btnGroupMiscellaneous, 1);
    }//GEN-LAST:event_btnGroupMiscellaneousActionPerformed

    private void btnGroupBarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupBarsActionPerformed
        expandCollapse(pnlMenuBars, btnGroupBars, 3);
    }//GEN-LAST:event_btnGroupBarsActionPerformed
// </editor-fold> 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // <editor-fold defaultstate="collapsed" desc="Private vars">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonut;
    private javax.swing.JButton btnGroupAreas;
    private javax.swing.JButton btnGroupBars;
    private javax.swing.JButton btnGroupBubbles;
    private javax.swing.JButton btnGroupGantt;
    private javax.swing.JButton btnGroupLines;
    private javax.swing.JButton btnGroupMiscellaneous;
    private javax.swing.JButton btnGroupPieDonut;
    private javax.swing.JButton btnGroupPoints;
    private javax.swing.JButton btnMultiDonut;
    private javax.swing.JButton btnMultiplePies;
    private javax.swing.JButton btnPopularCodeLanguages;
    private javax.swing.JButton btnProductShipments;
    private javax.swing.JButton btnProjectPlanner;
    private javax.swing.JButton btnSalesFigures;
    private javax.swing.JButton btnSalesFiguresPie;
    private javax.swing.JButton btnScroller;
    private javax.swing.JButton btnServerStatus;
    private javax.swing.JButton btnStackedBars;
    private javax.swing.JButton btnStockMonitoring;
    private javax.swing.JButton btnVegetationGrowth;
    private javax.swing.JButton btnWeb;
    private javax.swing.JButton btnWebAnalytics;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDescript;
    private javax.swing.JLabel lblImgTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlChart;
    private javax.swing.JPanel pnlContact;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuAreas;
    private javax.swing.JPanel pnlMenuBars;
    private javax.swing.JPanel pnlMenuBubbles;
    private javax.swing.JPanel pnlMenuGantt;
    private javax.swing.JPanel pnlMenuGroups;
    private javax.swing.JPanel pnlMenuLines;
    private javax.swing.JPanel pnlMenuMiscellaneous;
    private javax.swing.JPanel pnlMenuPieDonut;
    private javax.swing.JPanel pnlMenuPoints;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables
// </editor-fold> 

    JPanel pnlSample = null;

    private void setButtonsListeners() {
        ActionListener btnListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (e.getSource() == btnStockMonitoring) {
                    showChart(new StockMonitoring());
                } else if (e.getSource() == btnWebAnalytics) {
                    showChart(new WebAnalytics());
                } else if (e.getSource() == btnSalesFigures) {
                    showChart(new SalesFigures());
                } else if (e.getSource() == btnStackedBars) {
                    showChart(new StackedBars());
                } else if (e.getSource() == btnServerStatus) {
                    showChart(new ServerStatus());
                } else if (e.getSource() == btnVegetationGrowth) {
                    showChart(new VegetationGrowth());
                } else if (e.getSource() == btnSalesFiguresPie) {
                    showChart(new PieSalesFigures());
                } else if (e.getSource() == btnMultiplePies) {
                    showChart(new MultiPies());
                } else if (e.getSource() == btnDonut) {
                    showChart(new DonutChart());
                } else if (e.getSource() == btnMultiDonut) {
                    showChart(new MultiDonut());
                } else if (e.getSource() == btnProductShipments) {
                    showChart(new ProductShipments());
                } else if (e.getSource() == btnProjectPlanner) {
                    showChart(new ProjectPlanner());
                } else if (e.getSource() == btnPopularCodeLanguages) {
                    showChart(new PopularCodeLanguages());
                } else if (e.getSource() == btnScroller) {
                    showChart(new ScrollerChart());
                }

                setButtonsLocations();
            }
        };

        pnlTitle.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                showChart(new StartForm());
            }
        });

        btnStockMonitoring.addActionListener(btnListener);
        btnWebAnalytics.addActionListener(btnListener);
        btnSalesFigures.addActionListener(btnListener);
        btnStackedBars.addActionListener(btnListener);
        btnServerStatus.addActionListener(btnListener);
        btnVegetationGrowth.addActionListener(btnListener);
        btnSalesFiguresPie.addActionListener(btnListener);
        btnMultiplePies.addActionListener(btnListener);
        btnDonut.addActionListener(btnListener);
        btnMultiDonut.addActionListener(btnListener);
        btnProductShipments.addActionListener(btnListener);
        btnProjectPlanner.addActionListener(btnListener);
        btnPopularCodeLanguages.addActionListener(btnListener);
        btnScroller.addActionListener(btnListener);
    }

    private void setPlainFonts() {
        lblTitle.setFont(lblTitle.getFont().deriveFont(Font.PLAIN));

        setPlainFont(btnGroupLines);
        setPlainFont(btnStockMonitoring);
        setPlainFont(btnWebAnalytics);

        setPlainFont(btnGroupBars);
        setPlainFont(btnSalesFigures);
        setPlainFont(btnStackedBars);
        setPlainFont(btnServerStatus);

        setPlainFont(btnGroupAreas);
        setPlainFont(btnVegetationGrowth);

        setPlainFont(btnGroupPieDonut);
        setPlainFont(btnSalesFiguresPie);
        setPlainFont(btnMultiplePies);
        setPlainFont(btnDonut);
        setPlainFont(btnMultiDonut);

        setPlainFont(btnGroupPoints);
        setPlainFont(btnProductShipments);

        setPlainFont(btnGroupGantt);
        setPlainFont(btnProjectPlanner);

        setPlainFont(btnGroupBubbles);
        setPlainFont(btnPopularCodeLanguages);

        setPlainFont(btnGroupMiscellaneous);
        setPlainFont(btnScroller);

        lblContact.setFont(lblContact.getFont().deriveFont(Font.PLAIN, 10));
        lblDescript.setFont(lblDescript.getFont().deriveFont(Font.PLAIN, 10));
        btnWeb.setFont(btnWeb.getFont().deriveFont(Font.PLAIN, 10));
    }

    private void setPlainFont(JButton btn) {
        btn.setFont(btn.getFont().deriveFont(Font.PLAIN));
    }

    private void showChart(JPanel chart) {
        pnlChart.removeAll();

        pnlSample = chart;

        pnlChart.add(pnlSample);
        pnlChart.invalidate();
        pnlChart.validate();
        pnlChart.repaint();
    }

    private void expandCollapse(JPanel pnlMenu, JButton btnGroup, int nSamples) {
        int totalHeight = btnGroup.getHeight() + btnStockMonitoring.getHeight() * nSamples;
        if (pnlMenu.getHeight() == btnGroup.getHeight() + 2) {
            pnlMenu.setSize(pnlMenu.getWidth(), totalHeight);
            btnGroup.setIcon(new ImageIcon(getClass().getResource("/Resources/up.png")));
        } else {
            pnlMenu.setSize(pnlMenu.getWidth(), btnGroup.getHeight() + 2);
            btnGroup.setIcon(new ImageIcon(getClass().getResource("/Resources/down.png")));
        }

        setButtonsLocations();
    }
    
    private void setButtonsLocations() {
        pnlMenuBars.setLocation(pnlMenuBars.getX(), pnlMenuLines.getHeight());
        pnlMenuAreas.setLocation(pnlMenuAreas.getX(), pnlMenuBars.getY() + pnlMenuBars.getHeight());
        pnlMenuPieDonut.setLocation(pnlMenuPieDonut.getX(), pnlMenuAreas.getY() + pnlMenuAreas.getHeight());
        pnlMenuPoints.setLocation(pnlMenuPoints.getX(), pnlMenuPieDonut.getY() + pnlMenuPieDonut.getHeight());
        pnlMenuGantt.setLocation(pnlMenuGantt.getX(), pnlMenuPoints.getY() + pnlMenuPoints.getHeight());
        pnlMenuBubbles.setLocation(pnlMenuBubbles.getX(), pnlMenuGantt.getY() + pnlMenuGantt.getHeight());
        pnlMenuMiscellaneous.setLocation(pnlMenuMiscellaneous.getX(), pnlMenuBubbles.getY() + pnlMenuBubbles.getHeight());
    }

}
