/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StandardSeries.Miscellaneous;

import com.steema.teechart.ScrollMode;
import com.steema.teechart.TChart;
import com.steema.teechart.TextShapeStyle;
import com.steema.teechart.drawing.Color;
import com.steema.teechart.drawing.DashStyle;
import com.steema.teechart.drawing.GradientDirection;
import com.steema.teechart.drawing.StringAlignment;
import com.steema.teechart.editors.ChartEditor;
import com.steema.teechart.styles.Area;
import com.steema.teechart.styles.Bar;
import com.steema.teechart.styles.BarStyle;
import com.steema.teechart.styles.Bubble;
import com.steema.teechart.styles.Calendar;
import com.steema.teechart.styles.CircularGauge;
import com.steema.teechart.styles.CustomBar;
import com.steema.teechart.styles.Donut;
import com.steema.teechart.styles.Line;
import com.steema.teechart.styles.Pie;
import com.steema.teechart.styles.World;
import com.steema.teechart.styles.WorldMapType;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author norike
 */
public class StartForm extends javax.swing.JPanel {

    /**
     * Creates new form StartForm
     */
    public StartForm() {
        initComponents();
        
        createCharts();
        initCharts();        
        setEditors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlChart1 = new javax.swing.JPanel();
        pnlChart2 = new javax.swing.JPanel();
        pnlBottom = new javax.swing.JPanel();
        pnlUp = new javax.swing.JPanel();
        pnlChart3 = new javax.swing.JPanel();
        pnlChart4 = new javax.swing.JPanel();
        pnlDown = new javax.swing.JPanel();
        pnlChart5 = new javax.swing.JPanel();
        pnlChart6 = new javax.swing.JPanel();
        pnlRight = new javax.swing.JPanel();
        pnlChart7 = new javax.swing.JPanel();
        pnlChart8 = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        pnlChart1.setBackground(new java.awt.Color(153, 255, 204));
        pnlChart1.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 2);
        add(pnlChart1, gridBagConstraints);

        pnlChart2.setBackground(new java.awt.Color(0, 102, 255));
        pnlChart2.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        add(pnlChart2, gridBagConstraints);

        pnlBottom.setLayout(new java.awt.GridBagLayout());

        pnlUp.setBackground(new java.awt.Color(204, 204, 204));
        pnlUp.setOpaque(false);
        pnlUp.setLayout(new java.awt.GridBagLayout());

        pnlChart3.setBackground(new java.awt.Color(255, 102, 102));
        pnlChart3.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        pnlUp.add(pnlChart3, gridBagConstraints);

        pnlChart4.setBackground(new java.awt.Color(255, 153, 51));
        pnlChart4.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        pnlUp.add(pnlChart4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 2);
        pnlBottom.add(pnlUp, gridBagConstraints);

        pnlDown.setOpaque(false);
        pnlDown.setLayout(new java.awt.GridBagLayout());

        pnlChart5.setBackground(new java.awt.Color(204, 153, 255));
        pnlChart5.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        pnlDown.add(pnlChart5, gridBagConstraints);

        pnlChart6.setBackground(new java.awt.Color(255, 255, 255));
        pnlChart6.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        pnlDown.add(pnlChart6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 2);
        pnlBottom.add(pnlDown, gridBagConstraints);

        pnlRight.setLayout(new java.awt.GridBagLayout());

        pnlChart7.setBackground(new java.awt.Color(255, 105, 180));
        pnlChart7.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        pnlRight.add(pnlChart7, gridBagConstraints);

        pnlChart8.setBackground(new java.awt.Color(255, 105, 180));
        pnlChart8.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        pnlRight.add(pnlChart8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        pnlBottom.add(pnlRight, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        add(pnlBottom, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlChart1;
    private javax.swing.JPanel pnlChart2;
    private javax.swing.JPanel pnlChart3;
    private javax.swing.JPanel pnlChart4;
    private javax.swing.JPanel pnlChart5;
    private javax.swing.JPanel pnlChart6;
    private javax.swing.JPanel pnlChart7;
    private javax.swing.JPanel pnlChart8;
    private javax.swing.JPanel pnlDown;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlUp;
    // End of variables declaration//GEN-END:variables

    protected TChart tChart1, tChart2, tChart3, tChart4, tChart5, tChart6, tChart7, tChart8;
    
    private void createCharts() {
        tChart1 = new com.steema.teechart.TChart();
        tChart2 = new com.steema.teechart.TChart();
        tChart3 = new com.steema.teechart.TChart();
        tChart4 = new com.steema.teechart.TChart();
        tChart5 = new com.steema.teechart.TChart();
        tChart6 = new com.steema.teechart.TChart();
        tChart7 = new com.steema.teechart.TChart();
        tChart8 = new com.steema.teechart.TChart();

        pnlChart1.add(tChart1);
        pnlChart2.add(tChart2);
        pnlChart3.add(tChart3);
        pnlChart4.add(tChart4);
        pnlChart5.add(tChart5);
        pnlChart6.add(tChart6);
        pnlChart7.add(tChart7);
        pnlChart8.add(tChart8);
    }

    private void initCharts() {
        initChart1();
        initChart2();
        initChart3();
        initChart4();
        initChart5();
        initChart6();
        initChart7();
        initChart8();
    }

    private void setEditors() {
        setEditor(tChart1);
        setEditor(tChart2);
        setEditor(tChart3);
        setEditor(tChart4);
        setEditor(tChart5);
        setEditor(tChart6);
        setEditor(tChart7);
        setEditor(tChart8);
    }

    private void setEditor(TChart chart) {
        chart.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                 if (e.getClickCount()==2) {
                    ChartEditor.editChart(chart.getChart());
                }
            }
        });
    }

    private void initChart1() {
        tChart1.getAspect().setView3D(false);
        tChart1.getWalls().setVisible(false);
        tChart1.getPanel().setColor(new Color(102, 205, 170));
        tChart1.getHeader().setText("Bars and Lines");
        tChart1.getHeader().getFont().setName("Segoe UI");
        tChart1.getHeader().getFont().setColor(Color.WHITE);
        tChart1.getHeader().getFont().setSize(41);
        tChart1.getHeader().setTransparent(true);
        tChart1.getHeader().setAlignment(StringAlignment.NEAR);
        tChart1.getHeader().setCustomPosition(true);
        tChart1.getPanel().setMarginTop(19);
        tChart1.getLegend().setVisible(false);
        tChart1.getAxes().getBottom().getGrid().setVisible(false);
        tChart1.getAxes().getBottom().getAxisPen().setColor(Color.WHITE);
        tChart1.getAxes().getBottom().getAxisPen().setStyle(DashStyle.DOT);
        tChart1.getAxes().getBottom().getLabels().setVisible(false);
        tChart1.getAxes().getLeft().getGrid().setStyle(DashStyle.DOT);
        tChart1.getAxes().getLeft().getGrid().setColor(Color.WHITE);
        tChart1.getAxes().getLeft().getAxisPen().setVisible(false);
        tChart1.getAxes().getLeft().setIncrement(25);
        tChart1.getAxes().getLeft().getLabels().getFont().setColor(Color.WHITE);
        tChart1.getAxes().getLeft().getLabels().getFont().setSize(13);
        tChart1.getAxes().getLeft().getLabels().getFont().setName("Segoe UI");
        tChart1.getAxes().getLeft().getMinorTicks().setVisible(false);
        tChart1.getAxes().getLeft().getTicks().setTransparency(100);
        
        Bar bar1 = new Bar(tChart1.getChart());
        bar1.add(20);
        bar1.add(50);
        bar1.add(10);
        bar1.add(70);
        bar1.add(45);
        bar1.getGradient().setVisible(true);
        bar1.setBarStyle(BarStyle.ROUNDRECTANGLE);
        bar1.setRoundSize(10);
        bar1.setColor(Color.WHITE);
        bar1.getGradient().setEndColor(new Color(102, 205, 170));
        bar1.getPen().setVisible(false);
        bar1.getMarks().getArrow().setVisible(false);
        bar1.getMarks().getPen().setVisible(false);
        bar1.getMarks().setColor(Color.WHITE);
        bar1.getMarks().setShapeStyle(TextShapeStyle.ROUNDRECTANGLE);
        bar1.getMarks().setBorderRound(4);
        bar1.getMarks().getFont().setColor(new Color(102, 205, 170));
        bar1.getMarks().getFont().setName("Arial");
        bar1.getMarks().getShadow().setVisible(false);
        
        Line line1 = new Line(tChart1.getChart());
        line1.add(0, 45);
        line1.add(0.444, 55);
        line1.add(0.889, 75);
        line1.add(1.333, 65);
        line1.add(1.778, 45);
        line1.add(2.222, 80);
        line1.add(2.667, 85);
        line1.add(3.111, 98);
        line1.add(3.556, 75);
        line1.add(4, 68);
        line1.setColor(Color.WHITE);
        line1.getLinePen().setWidth(2);
        line1.setSmoothed(true);
    }

    private void initChart2() {
        tChart2.getWalls().setVisible(false);
        tChart2.getLegend().setVisible(false);
        tChart2.getHeader().setAlignment(StringAlignment.NEAR);
        tChart2.getHeader().setCustomPosition(true);
        tChart2.getHeader().getFont().setColor(Color.WHITE);
        tChart2.getHeader().getFont().setSize(41);
        tChart2.getHeader().getFont().setName("Segoe UI");
        tChart2.getHeader().setLeft(0);
        tChart2.getHeader().setText("Maps");
        tChart2.getPanel().setMarginTop(3);
        tChart2.getPanel().setMarginBottom(0);
        tChart2.getPanel().setMarginLeft(18);
        tChart2.getAxes().setVisible(false);
        tChart2.getPanel().setColor(new Color(0, 102, 204));
        
        World world1 = new World(tChart2.getChart());
        try {
            world1.setMap(WorldMapType.WORLD);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StartForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(StartForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        world1.getPen().setColor(new Color(0, 102, 204));
    }

    private void initChart3() {
        tChart3.getHeader().setVisible(false);
        tChart3.getFooter().getFont().setColor(Color.WHITE);
        tChart3.getFooter().getFont().setSize(25);
        tChart3.getFooter().getFont().setName("Segoe UI");
        tChart3.getFooter().setText("Gauges");
        tChart3.getPanel().setColor(new Color(220, 20, 60));
        
        CircularGauge circGauge1 = new CircularGauge(tChart3.getChart());
        circGauge1.getCenter().setHorizSize(11);
        circGauge1.getCenter().setVertSize(11);
        circGauge1.getCenter().getGradient().setStartColor(Color.WHITE);
        circGauge1.getCenter().getGradient().setEndColor(new Color(199, 199, 199));
        circGauge1.getCenter().getShadow().setColor(new Color(192, 192, 192));
        circGauge1.getCenter().getShadow().setTransparency(50);
        circGauge1.getCenter().getShadow().setHorizSize(2);
        circGauge1.getCenter().getShadow().setVertSize(2);
        circGauge1.getFrame().getMiddleBand().setVisible(false);
        circGauge1.getFrame().getOuterBand().setVisible(false);
        circGauge1.getFrame().getInnerBand().setColor(Color.WHITE);
        circGauge1.getFaceBrush().getGradient().setVisible(false);
        circGauge1.getFaceBrush().setColor(new Color(220, 20, 60));
        circGauge1.getAxis().getLabels().getFont().setColor(new Color(192, 192, 192));
        circGauge1.getAxis().getLabels().getFont().setBold(true);
        circGauge1.getAxis().getLabels().getFont().setName("Verdana");
        circGauge1.getTicks().getPen().setColor(Color.WHITE);
        circGauge1.getMinorTicks().setColor(Color.WHITE);
        circGauge1.getMinorTicks().getPen().setVisible(false);
        circGauge1.getHand().getBrush().getGradient().setVisible(false);
        circGauge1.getHand().getBrush().setColor(Color.GRAY);
        circGauge1.getHand().setHorizSize(4);
        circGauge1.getGreenLine().getPen().setVisible(false);
        circGauge1.getGreenLine().setVertSize(4);
        circGauge1.getGreenLine().getBrush().getGradient().setStartColor(Color.SILVER);
        circGauge1.getGreenLine().getBrush().getGradient().setEndColor(Color.WHITE);
        circGauge1.getRedLine().getPen().setVisible(false);
        circGauge1.getRedLine().setVertSize(4);
        circGauge1.getRedLine().setHorizSize(10);
        circGauge1.getRedLine().getBrush().getGradient().setStartColor(Color.SILVER);
        circGauge1.getRedLine().getBrush().getGradient().setEndColor(new Color(100, 100, 100));
        
        circGauge1.setValue(35);
    }

    private void initChart4() {
        tChart4.getPanel().setMarginTop(0);
        tChart4.getPanel().setColor(new Color(255, 165, 0));
        tChart4.getAspect().setView3D(false);
        tChart4.getWalls().setVisible(false);
        tChart4.getLegend().setVisible(false);
        tChart4.getHeader().setAlignment(StringAlignment.NEAR);
        tChart4.getHeader().getFont().setColor(Color.WHITE);
        tChart4.getHeader().getFont().setSize(31);
        tChart4.getHeader().getFont().setName("Segoe UI");
        tChart4.getHeader().setText("Bubbles and Gantt styles");
        tChart4.getAxes().getBottom().getAxisPen().setVisible(false);
        tChart4.getAxes().getBottom().getLabels().getFont().setColor(new Color(255, 165, 0));
        tChart4.getAxes().getBottom().getGrid().setColor(Color.WHITE);
        tChart4.getAxes().getBottom().getTicks().setVisible(false);
        tChart4.getAxes().getBottom().getMinorTicks().setVisible(false);
        tChart4.getAxes().getLeft().getAxisPen().setVisible(false);
        tChart4.getAxes().getLeft().getLabels().getFont().setColor(new Color(255, 165, 0));
        tChart4.getAxes().getLeft().getGrid().setColor(Color.WHITE);
        tChart4.getAxes().getLeft().getTicks().setVisible(false);
        tChart4.getAxes().getLeft().getMinorTicks().setVisible(false);
        
        Bubble bubble1 = new Bubble(tChart4.getChart());
        bubble1.add(0, 501, 166);
        bubble1.add(1, 881, 500);
        bubble1.add(2, 947, 220);
        bubble1.add(3, 385, 450);
        bubble1.add(4, 516, 166);
        bubble1.add(5, 947, 370);
        bubble1.getPointer().setInflateMargins(true);
        bubble1.setColorEach(false);
        bubble1.getPointer().getPen().setVisible(false);
        bubble1.getPointer().getBrush().getGradient().setVisible(true);
        bubble1.getPointer().getBrush().getGradient().setStartColor(new Color(255, 165, 0));
        bubble1.getPointer().getBrush().getGradient().setDirection(GradientDirection.FORWARDDIAGONAL);
    }

    private void initChart5() {
        tChart5.getPanning().setAllow(ScrollMode.HORIZONTAL);
        tChart5.getPanel().setMarginTop(0);
        tChart5.getPanel().setMarginLeft(2);
        tChart5.getPanel().setMarginRight(2);
        tChart5.getPanel().setMarginBottom(8);
        tChart5.getHeader().setAlignment(StringAlignment.FAR);
        tChart5.getHeader().getFont().setColor(Color.WHITE);
        tChart5.getHeader().getFont().setSize(31);
        tChart5.getHeader().getFont().setName("Segoe UI");
        tChart5.getHeader().setText("Areas and Points");
        tChart5.getWalls().setVisible(false);
        tChart5.getAspect().setView3D(false);
        tChart5.getPanel().setColor(new Color(186, 85, 211));
        tChart5.getAxes().getBottom().getAxisPen().setColor(Color.WHITE);
        tChart5.getAxes().getBottom().getAxisPen().setWidth(1);
        tChart5.getAxes().getBottom().getGrid().setColor(new Color(169, 169, 169));
        tChart5.getAxes().getBottom().setIncrement(10);
        tChart5.getAxes().getBottom().getLabels().getFont().setColor(Color.WHITE);
        tChart5.getAxes().getBottom().getLabels().getFont().setSize(13);
        tChart5.getAxes().getBottom().getLabels().getFont().setName("Segoe UI");
        tChart5.getAxes().getBottom().setMinMax(5, 20);
        tChart5.getAxes().getLeft().setVisible(false);
        tChart5.getAxes().getLeft().setMaximumOffset(3);
        tChart5.getLegend().setVisible(false);
        
        Area area1 = new Area(tChart5.getChart());
        area1.getGradient().setStartColor(new Color(186, 85, 211));
        area1.getGradient().setVisible(true);
        area1.getAreaLinesPen().setVisible(false);
        area1.getLinePen().setColor(Color.WHITE);
        area1.add(new double[]{662, 663, 659, 639, 648, 638, 654, 638, 619,
            625, 641, 658, 667, 652, 644, 628, 622, 636, 641, 621, 631, 618,
            601, 609, 591});
        area1.setSmoothed(true);
        
        Area area2 = new Area(tChart5.getChart());
        area2.getGradient().setStartColor(new Color(186, 85, 211));
        area2.getGradient().setVisible(true);
        area2.getAreaLinesPen().setVisible(false);
        area2.getLinePen().setColor(Color.WHITE);
        area2.add(new double[] {601, 601, 604, 607, 615, 622, 613, 614, 618,
            609, 611, 606, 610, 617, 614, 621, 629, 624, 618, 623, 626, 633,
            633, 635, 642});
        area2.setSmoothed(true);
    }

    private void initChart6() {
        tChart6.getPanel().getGradient().setVisible(false);
        tChart6.getPanel().setColor(Color.WHITE);
        tChart6.getWalls().setVisible(false);
        tChart6.getFooter().setAlignment(StringAlignment.FAR);
        tChart6.getFooter().getFont().setColor(new Color(0, 128, 192));
        tChart6.getFooter().getFont().setSize(31);
        tChart6.getFooter().getFont().setName("Segoe UI");
        tChart6.getFooter().setText("Calendars");
        tChart6.getHeader().setVisible(false);
        
        Calendar calendar1 = new Calendar(tChart6.getChart());
        calendar1.getPen().setVisible(false);
        calendar1.getDays().getFont().setColor(new Color(0, 128, 192));
        calendar1.getMonths().getFont().setColor(new Color(0, 128, 192));
        calendar1.getMonths().getFont().setSize(13);
        calendar1.getMonths().getFont().setName("Segoe UI");
        calendar1.getSunday().setColor(new Color(68, 102, 163));
        calendar1.getSunday().getPen().setVisible(false);
        calendar1.getToday().setColor(new Color(227, 28, 33));
        calendar1.getToday().getPen().setVisible(false);
        calendar1.getTrailing().getFont().setColor(Color.GRAY);
        calendar1.getWeekDays().setColor(Color.SILVER);
        calendar1.getWeekDays().getFont().setColor(new Color(0, 128, 192));
        calendar1.getWeekDays().setTransparent(false);
        calendar1.getWeekDays().getPen().setVisible(false);
        calendar1.getPreviousMonthButton().setVisible(true);
        calendar1.getPreviousMonthButton().setBackground(Color.WHITE);
        calendar1.getPreviousMonthButton().setBorderPainted(false);
        calendar1.getPreviousMonthButton().setFocusPainted(false);
        calendar1.getPreviousMonthButton().setLocation(0, 6);
        calendar1.getNextMonthButton().setVisible(true);
        calendar1.getNextMonthButton().setBackground(Color.WHITE);
        calendar1.getNextMonthButton().setBorderPainted(false);
        calendar1.getNextMonthButton().setFocusPainted(false);
        calendar1.getNextMonthButton().setLocation(42, 6);
    }

    private void initChart7() {
        tChart7.getPanel().setMarginTop(0);
        tChart7.getPanel().setColor(new Color(255, 105, 180));
        tChart7.getHeader().getFont().setColor(Color.WHITE);
        tChart7.getHeader().getFont().setSize(31);
        tChart7.getHeader().getFont().setName("Segoe UI");
        tChart7.getHeader().setText("Pies and Donuts");
        tChart7.getLegend().setVisible(false);
        tChart7.getAspect().setView3D(false);
        
        Pie pie1 = new Pie(tChart7.getChart());
        populateCircled(pie1);
        pie1.setCircled(true);
        pie1.getMarks().getFont().setColor(new Color(255, 105, 180));
        pie1.getMarks().getFont().setSize(13);
        pie1.getMarks().getFont().setName("Segoe UI");
        pie1.getMarks().setTransparent(true);
        //pie1.getMarks().setInsideSlice(true); //B1164
        //pie1.getMarks().setRotated(true); //B1165
        pie1.getMarks().setArrowLength(-60);
        pie1.setCustomXRadius(100);
        
        pie1.getMarks().getArrow().setVisible(false);
        pie1.getPen().setColor(new Color(255, 105, 180)); //B1166
        pie1.setAutoPenColor(false);
        pie1.getPen().setWidth(3);
        pie1.setRotationAngle(233);
    }

    private void initChart8() {
        tChart8.getPanel().setColor(new Color(255, 105, 180));
        tChart8.getHeader().setVisible(false);
        tChart8.getLegend().setVisible(false);
        tChart8.getAspect().setView3D(false);
        
        Donut donut1 = new Donut(tChart8.getChart());
        populateCircled(donut1);
        donut1.setCircled(true);
        donut1.getMarks().getFont().setColor(Color.WHITE);
        donut1.getMarks().setTransparent(true);
        donut1.getMarks().getCallout().setArrowHeadSize(10);
        donut1.getMarks().setArrowLength(17);
        donut1.getMarks().getArrow().setColor(Color.WHITE);
        donut1.getMarksPie().setLegSize(13);
        donut1.getMarksPie().setVertCenter(true);
        donut1.getPen().setColor(new Color(255, 105, 180)); //B1166
        donut1.setAutoPenColor(false);
        donut1.getPen().setWidth(3);
        donut1.setRotationAngle(233);
    }
    
    private void populateCircled(Pie series) {
        series.add(476, "Cars", Color.WHITE);
        series.add(883, "Phones", new Color(242, 242, 242));
        series.add(537, "Tables", new Color(223, 223, 223));
        series.add(364, "Monitors", new Color(215, 215, 215));
    }
}
