/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StandardSeries.PieAndDonut;

import com.steema.teechart.TChart;
import com.steema.teechart.TextShapeStyle;
import com.steema.teechart.drawing.Color;
import com.steema.teechart.editors.ChartEditor;
import com.steema.teechart.legend.LegendAlignment;
import com.steema.teechart.styles.Bar;
import com.steema.teechart.styles.MarksStyle;
import com.steema.teechart.styles.Pie;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author norike
 */
public class MultiPies extends javax.swing.JPanel {

    /**
     * Creates new form MultiplePies
     */
    public MultiPies() {
        initComponents();
        
        createCharts();
        initCharts();        
        setEditors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTop = new javax.swing.JPanel();
        labelTop = new javax.swing.JLabel();
        pnlChartTop = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pnlChart1 = new javax.swing.JPanel();
        pnlChart2 = new javax.swing.JPanel();
        pnlChart3 = new javax.swing.JPanel();
        pnlChart4 = new javax.swing.JPanel();
        pnlChart5 = new javax.swing.JPanel();
        pnlChart6 = new javax.swing.JPanel();

        pnlTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop.setLayout(new java.awt.BorderLayout());

        labelTop.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        labelTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTop.setText("Women are more likely to attend the day classes while men are more commontly found in the evening class");
        labelTop.setPreferredSize(new java.awt.Dimension(749, 37));
        pnlTop.add(labelTop, java.awt.BorderLayout.NORTH);

        pnlChartTop.setPreferredSize(new java.awt.Dimension(0, 34));
        pnlChartTop.setLayout(new java.awt.BorderLayout());
        pnlTop.add(pnlChartTop, java.awt.BorderLayout.SOUTH);

        jPanel8.setLayout(new java.awt.GridBagLayout());

        pnlChart1.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel8.add(pnlChart1, gridBagConstraints);

        pnlChart2.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel8.add(pnlChart2, gridBagConstraints);

        pnlChart3.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel8.add(pnlChart3, gridBagConstraints);

        pnlChart4.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel8.add(pnlChart4, gridBagConstraints);

        pnlChart5.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel8.add(pnlChart5, gridBagConstraints);

        pnlChart6.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel8.add(pnlChart6, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 339, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel labelTop;
    private javax.swing.JPanel pnlChart1;
    private javax.swing.JPanel pnlChart2;
    private javax.swing.JPanel pnlChart3;
    private javax.swing.JPanel pnlChart4;
    private javax.swing.JPanel pnlChart5;
    private javax.swing.JPanel pnlChart6;
    private javax.swing.JPanel pnlChartTop;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables

    protected TChart tChartTop, tChart1, tChart2, tChart3, tChart4, tChart5, tChart6;
    
    private void createCharts() {
        tChartTop = new TChart();
        pnlChartTop.add(tChartTop);
        
        tChart1 = new TChart();
        pnlChart1.add(tChart1);
        
        tChart2 = new TChart();
        pnlChart2.add(tChart2);
        
        tChart3 = new TChart();
        pnlChart3.add(tChart3);
        
        tChart4 = new TChart();
        pnlChart4.add(tChart4);
        
        tChart5 = new TChart();
        pnlChart5.add(tChart5);
        
        tChart6 = new TChart();
        pnlChart6.add(tChart6);
    }

    private void initCharts() {
        initChartTop();
        initChart1();
        initChart2();
        initChart3();
        initChart4();
        initChart5();
        initChart6();
    }

    private void setEditors() {
        setEditor(tChartTop);
        setEditor(tChart1);
        setEditor(tChart2);
        setEditor(tChart3);
        setEditor(tChart4);
        setEditor(tChart5);
        setEditor(tChart6);
    }
    
    private void setEditor(TChart chart) {
        chart.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                 if (e.getClickCount()==2) {
                    ChartEditor.editChart(chart.getChart());
                }
            }
        });
    }

    private void initChartTop() {
        tChartTop.getHeader().setVisible(false);
        tChartTop.getAspect().setView3D(false);
        tChartTop.getPanel().getGradient().setVisible(false);
        tChartTop.getLegend().setAlignment(LegendAlignment.TOP);
        tChartTop.getLegend().getFont().setColor(Color.GRAY);
        tChartTop.getLegend().getFont().setSize(16);
        tChartTop.getLegend().getFont().setName("Segoe UI");
        tChartTop.getLegend().getPen().setVisible(false);
        tChartTop.getLegend().getSymbol().getPen().setVisible(false);
        tChartTop.getLegend().setTransparent(true);
        tChartTop.getAxes().setVisible(false);
        tChartTop.getPanel().setColor(Color.WHITE);
  
        Bar bar1 = new Bar(tChartTop.getChart());
        bar1.getPen().setVisible(false);
        bar1.setTitle("Women");
        
        Bar bar2 = new Bar(tChartTop.getChart());
        bar2.getPen().setVisible(false);
        bar2.setTitle("Men");

    }
    
    private void initChart1() {
        initPie(tChart1);
        tChart1.getHeader().setText("Morning Class");
        tChart1.getSeries(0).add(new int[]{70, 25});
    }
    
    private void initChart2() {
        initPie(tChart2);
        tChart2.getHeader().setText("Afternoon Class");
        tChart2.getSeries(0).add(new int[]{65, 30});
    }
    
    private void initChart3() {
        initPie(tChart3);
        tChart3.getHeader().setText("Evening Class");
        tChart3.getSeries(0).add(new int[]{40, 55});
    }
    
    private void initChart4() {
        initBars(tChart4);
        tChart4.getFooter().setText("Morning Class");
        tChart4.getSeries(0).setDataSource(tChart1.getSeries(0));
    }
    
    private void initChart5() {
        initBars(tChart5);
        tChart5.getFooter().setText("Afternoon Class");
        tChart5.getSeries(0).setDataSource(tChart2.getSeries(0));
    }
    
    private void initChart6() {
        initBars(tChart6);
        tChart6.getFooter().setText("Evening Class");
        tChart6.getSeries(0).setDataSource(tChart3.getSeries(0));
    }

    private void initPie(TChart tChart) {
        tChart.getPanel().getGradient().setVisible(false);
        tChart.getHeader().getFont().setColor(Color.GRAY);
        tChart.getHeader().getFont().setName("Verdana");
        tChart.getLegend().setVisible(false);
        tChart.getAspect().setView3D(false);
        tChart.getPanel().setColor(Color.WHITE);
        
        Pie pie = new Pie(tChart.getChart());
        pie.getMarks().setVisible(false);
        pie.getPen().setColor(Color.WHITE);
        pie.getPen().setWidth(4);
        pie.setRotationAngle(91);
        pie.setCircled(true);
    }
    
    private void initBars(TChart tChart) {
        tChart.getWalls().setVisible(false);
        tChart.getHeader().setVisible(false);
        tChart.getFooter().getFont().setColor(Color.GRAY);
        tChart.getFooter().getFont().setName("Segoe UI");
        tChart.getPanel().getGradient().setVisible(false);
        //MarginBottom = 6
        tChart.getAxes().getBottom().setVisible(false);
        tChart.getAxes().getLeft().getGrid().setVisible(false);
        tChart.getAxes().getLeft().setIncrement(20);
        tChart.getAxes().getLeft().getMinorTicks().setVisible(false);
        tChart.getAxes().getLeft().getTicksInner().setColor(new Color(169, 169, 169));
        tChart.getLegend().setVisible(false);
        tChart.getAspect().setView3D(false);
        tChart.getPanel().setColor(Color.WHITE);
        
        if (tChart == tChart4) {
            tChart.getAxes().getLeft().getAxisPen().setColor(new Color(64, 64, 64));
            tChart.getAxes().getLeft().getAxisPen().setWidth(1);
            tChart.getAxes().getLeft().getLabels().getFont().setColor(Color.GRAY);
            tChart.getAxes().getLeft().getLabels().getFont().setName("Verdana");
        }
        else {
            tChart.getAxes().getLeft().getAxisPen().setVisible(false);
            tChart.getAxes().getLeft().getLabels().getFont().setColor(Color.WHITE);
        }
  
        Bar bar = new Bar(tChart.getChart());
        bar.getPen().setColor(Color.WHITE);
        bar.getPen().setWidth(4);
        bar.setColorEach(true);
        bar.getMarks().getPen().setVisible(false);
        bar.getMarks().setColor(Color.WHITE);
        bar.getMarks().setShapeStyle(TextShapeStyle.ROUNDRECTANGLE);
        bar.getMarks().setBorderRound(4);
        bar.getMarks().getShadow().setVisible(false);
        bar.getMarks().setStyle(MarksStyle.VALUE);
        bar.getMarks().getArrow().setVisible(false);
        bar.getMarks().getCallout().setLength(-24);
        bar.setBarWidthPercent(95);
    }
}
