/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StandardSeries.PieAndDonut;

import com.steema.teechart.TChart;
import com.steema.teechart.TextShapeStyle;
import com.steema.teechart.drawing.Color;
import com.steema.teechart.drawing.EdgeStyle;
import com.steema.teechart.editors.ChartEditor;
import com.steema.teechart.legend.LegendAlignment;
import com.steema.teechart.styles.NumericGauge;
import com.steema.teechart.styles.Pie;
import com.steema.teechart.themes.ColorPalettes;
import com.steema.teechart.themes.Theme;
import com.steema.teechart.tools.SubChart;
import com.steema.teechart.tools.SubChartTool;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author norike
 */
public class PieSalesFigures extends javax.swing.JPanel {

    /**
     * Creates new form SalesFiguresPie
     */
    public PieSalesFigures() {
        initComponents();
        
        createCharts();
        initCharts();        
        setEditor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        
        int horizMargin = 5;
        int vertMargin = 5;
        
        SubChart subChart1 = subChartTool1.getCharts().get(0);
        subChart1.setLeft(this.getWidth() - tChart2.getWidth() - horizMargin);
        subChart1.setTop(this.getHeight() / 3 - tChart2.getHeight() - vertMargin);
        
        SubChart subChart2 = subChartTool1.getCharts().get(1);
        subChart2.setLeft(this.getWidth() - tChart3.getWidth() - horizMargin);
        subChart2.setTop(this.getHeight() / 3 + vertMargin);
        
        //Blue Gauge
        NumericGauge numGauge1 = (NumericGauge)tChart2.getSeries(0);
        numGauge1.getTextMarker().getShape().setCustomPosition(true);
        numGauge1.getTextMarker().setLeft(subChart1.getLeft() + horizMargin);
        numGauge1.getTextMarker().setTop(subChart1.getTop() + vertMargin);
        
        numGauge1.getUnitsMarker().getShape().setCustomPosition(true);
        int tmpWidth = numGauge1.getUnitsMarker().getWidth();
        int tmpHeight = numGauge1.getUnitsMarker().getHeight();
        if (tmpWidth == 0) {
            tmpWidth = 96;
        }
        if (tmpHeight == 0) {
            tmpHeight = 29;
        }
        numGauge1.getUnitsMarker().getShape().setLeft(subChart1.getLeft() + subChart1.getWidth() - tmpWidth - horizMargin);
        numGauge1.getUnitsMarker().getShape().setTop(subChart1.getTop() + subChart1.getHeight() - tmpHeight - vertMargin);
        
        numGauge1.getValueMarker().getShape().setCustomPosition(true);
        tmpWidth = numGauge1.getValueMarker().getWidth();
        int tmpTop = numGauge1.getTextMarker().getShape().getTop();
        if (tmpWidth == 0) {
            tmpWidth = 158;
        }
        numGauge1.getValueMarker().getShape().setLeft(subChart1.getLeft() + subChart1.getWidth() - tmpWidth - horizMargin);
        numGauge1.getValueMarker().getShape().setTop(tmpTop);
        
        //Red Gauge
        NumericGauge numGauge2 = (NumericGauge)tChart3.getSeries(0);
        numGauge2.getTextMarker().getShape().setCustomPosition(true);
        numGauge2.getTextMarker().setLeft(subChart2.getLeft() + horizMargin);
        numGauge2.getTextMarker().setTop(subChart2.getTop() + vertMargin);
        
        numGauge2.getUnitsMarker().getShape().setCustomPosition(true);
        tmpWidth = numGauge2.getUnitsMarker().getWidth();
        tmpHeight = numGauge2.getUnitsMarker().getHeight();
        if (tmpWidth == 0) {
            tmpWidth = 70;
        }
        if (tmpHeight == 0) {
            tmpHeight = 29;
        }
        numGauge2.getUnitsMarker().getShape().setLeft(subChart2.getLeft() + subChart2.getWidth() - tmpWidth - horizMargin);
        numGauge2.getUnitsMarker().getShape().setTop(subChart2.getTop() + subChart2.getHeight() - tmpHeight - vertMargin);
        
        numGauge2.getValueMarker().getShape().setCustomPosition(true);
        tmpWidth = numGauge2.getValueMarker().getWidth();
        tmpTop = numGauge2.getTextMarker().getShape().getTop();
        if (tmpWidth == 0) {
            tmpWidth = 158;
        }
        numGauge2.getValueMarker().getShape().setLeft(subChart2.getLeft() + subChart2.getWidth() - tmpWidth - horizMargin);
        numGauge2.getValueMarker().getShape().setTop(tmpTop);
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    protected TChart tChart1, tChart2, tChart3;
    protected SubChartTool subChartTool1;
            
    private void createCharts() {
        tChart1 = new TChart();
        add(tChart1);
        
        subChartTool1 = new SubChartTool(tChart1.getChart());
        tChart2 = subChartTool1.getCharts().addChart("tChart2");
        tChart3 = subChartTool1.getCharts().addChart("tChart3");
        
        tChart2.setWidth(289);
        tChart2.setHeight(111);
        tChart3.setWidth(289);
        tChart3.setHeight(111);
    }

    private void initCharts() {
        initChart1();
        initChart2();
        initChart3();
    }

    private void setEditor() {
        tChart1.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                 if (e.getClickCount()==2) {
                    ChartEditor.editChart(tChart1.getChart());
                }
            }
        });
    }

    private void initChart1() {
        tChart1.getPanel().getBrush().loadImage(getClass().getResource("/Resources/world-map.png"));
        tChart1.getWalls().setVisible(false);
        tChart1.getPanel().getGradient().setVisible(false);
        tChart1.getPanel().setMarginTop(3);
        tChart1.getPanel().setMarginRight(18);
        tChart1.getSubHeader().getFont().setColor(Color.SILVER);
        tChart1.getSubHeader().getFont().setSize(19);
        tChart1.getSubHeader().getFont().setName("Segoe UI");
        tChart1.getSubHeader().getFont().getShadow().setColor(Color.GRAY);
        tChart1.getSubHeader().setText("actively using social media");
        tChart1.getHeader().getFont().setColor(Color.SILVER);
        tChart1.getHeader().getFont().setSize(31);
        tChart1.getHeader().getFont().setName("Segoe UI");
        tChart1.getHeader().getFont().getShadow().setColor(new Color(131, 131, 131));
        tChart1.getHeader().getFont().getShadow().setTransparency(50);
        tChart1.getHeader().getFont().getShadow().setHorizSize(1);
        tChart1.getHeader().getFont().getShadow().setSmoothBlur(2);
        tChart1.getHeader().getFont().getShadow().setVertSize(1);
        tChart1.getHeader().setText("Percentage of world population");
        tChart1.getLegend().setAlignment(LegendAlignment.BOTTOM);
        tChart1.getLegend().getFont().setColor(Color.SILVER);
        tChart1.getLegend().getFont().setSize(19);
        tChart1.getLegend().getFont().setName("Segoe UI");
        tChart1.getLegend().getPen().setVisible(false);
        tChart1.getLegend().getShadow().setVisible(false);
        tChart1.getLegend().getSymbol().getPen().setVisible(false);
        tChart1.getLegend().setTransparent(true);
        tChart1.getAspect().setView3D(false);
  
        Pie pie1 = new Pie(tChart1.getChart());
        pie1.setCircled(true);
        pie1.getMarks().getFont().setSize(16);
        pie1.getMarks().getFont().setName("Roboto Th");
        pie1.getMarks().getFont().setBold(true);
        pie1.getMarks().getPen().setVisible(false);
        pie1.getMarks().setShapeStyle(TextShapeStyle.ROUNDRECTANGLE);
        pie1.getMarks().setBorderRound(18);
        pie1.getMarks().getShadow().setVisible(false);
        pie1.getMarks().getBrush().setTransparency(48);
        pie1.getMarks().getArrow().setColor(new Color(192, 192, 192));
        pie1.getMarks().getArrow().setTransparency(48);
        pie1.getMarks().getArrow().setWidth(2);
        pie1.getMarks().setBackColor(Color.NAVY);
        pie1.getMarks().getCallout().setArrowHeadSize(7);
        pie1.getMarks().getCallout().setDistance(9);
        pie1.getMarks().getCallout().setLength(30);
        pie1.getMarks().getBrush().setColor(Color.NAVY);
        pie1.getShadow().setVisible(false);
        pie1.setEdgeStyle(EdgeStyle.FLAT);
        pie1.getOtherSlice().getLegend().setVisible(false);
        pie1.getMarksPie().setVertCenter(true);
        pie1.getPen().setVisible(false);
        
        pie1.add(19, "Facebook");
        pie1.add(14, "Tencent");
        pie1.add(9, "WhatsApp");
        pie1.add(5, "LinkedIn");
        pie1.add(4, "Twitter");

        pie1.getMarksPie().setLegSize(20);
        pie1.getMarks().setFontSeriesColor(true);
        
        ColorPalettes.applyPalette(tChart1.getChart(), Theme.AndroidPalette);
    }
    
    private void initChart2() {
        tChart2.getAspect().setView3D(false);
        tChart2.getPanel().getGradient().setVisible(false);
        tChart2.getHeader().setVisible(false);
        tChart2.getPanel().setColor(new Color(51, 181, 229));
        
        NumericGauge numGauge1 = new NumericGauge(tChart2.getChart());
        numGauge1.getFrame().setVisible(false);
        numGauge1.getFaceBrush().setVisible(false);
        
        numGauge1.getTextMarker().setText("Highest");
        numGauge1.getTextMarker().getShape().getBrush().setColor(new Color(181, 209, 151));
        numGauge1.getTextMarker().getShape().getFont().setName("Segoe UI");
        numGauge1.getTextMarker().getShape().getFont().setSize(17);
        numGauge1.getTextMarker().getShape().getFont().setColor(new Color(70, 95, 152));
        numGauge1.getTextMarker().setUsePalette(false);
        
        numGauge1.getUnitsMarker().setText("Facebook");
        numGauge1.getUnitsMarker().getShape().setTransparent(true);
        numGauge1.getUnitsMarker().getShape().getFont().setName("Segoe UI");
        numGauge1.getUnitsMarker().getShape().getFont().setSize(20);
        numGauge1.getUnitsMarker().getShape().getFont().setColor(Color.WHITE);
        numGauge1.getUnitsMarker().setUsePalette(false);
        
        numGauge1.setValue(712.5);
        numGauge1.getValueMarker().getShape().setTransparent(true);
        numGauge1.getValueMarker().getShape().getFont().setName("Segoe UI");
        numGauge1.getValueMarker().getShape().getFont().setSize(60);
        numGauge1.getValueMarker().getShape().getFont().setColor(Color.WHITE);
        numGauge1.getValueMarker().setUsePalette(false);
        
        numGauge1.getBrush().setVisible(false);
    }
    
    private void initChart3() {
        tChart3.getAspect().setView3D(false);
        tChart3.getPanel().getGradient().setVisible(false);
        tChart3.getHeader().setVisible(false);
        tChart3.getPanel().setColor(new Color(255, 68, 68));
        
        NumericGauge numGauge1 = new NumericGauge(tChart3.getChart());
        numGauge1.getFrame().setVisible(false);
        numGauge1.getFaceBrush().setVisible(false);
        
        numGauge1.getTextMarker().setText("Lowest");
        numGauge1.getTextMarker().getShape().getBrush().setColor(new Color(181, 209, 151));
        numGauge1.getTextMarker().getShape().getFont().setName("Segoe UI");
        numGauge1.getTextMarker().getShape().getFont().setSize(17);
        numGauge1.getTextMarker().getShape().getFont().setColor(new Color(70, 95, 152));
        numGauge1.getTextMarker().setUsePalette(false);
        
        numGauge1.getUnitsMarker().setText("Twitter");
        numGauge1.getUnitsMarker().getShape().setTransparent(true);
        numGauge1.getUnitsMarker().getShape().getFont().setName("Segoe UI");
        numGauge1.getUnitsMarker().getShape().getFont().setSize(20);
        numGauge1.getUnitsMarker().getShape().getFont().setColor(Color.WHITE);
        numGauge1.getUnitsMarker().setUsePalette(false);
        
        numGauge1.setValue(557.5);
        numGauge1.getValueMarker().getShape().setTransparent(true);
        numGauge1.getValueMarker().getShape().getFont().setName("Segoe UI");
        numGauge1.getValueMarker().getShape().getFont().setSize(60);
        numGauge1.getValueMarker().getShape().getFont().setColor(Color.WHITE);
        numGauge1.getValueMarker().setUsePalette(false);
        
        numGauge1.getBrush().setVisible(false);
    }
}
